# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3b774ff54a3e20f5e4bfdcebce60e86e5debddb0cc1d00cf744583f22a691a2191cb5c29b777bd1c23351334f5f86531b1f6710f5af74dd4b04b28516d790be

test:
  secret_key_base: 809c462fcaeb9f2feae6dc56ffabb19cb26be50be3b935e5bc01cb81066fa16bad4b916b5c39e8323ffb1888b1ff4d8da8aad69c36cf306f4c3b796e392443a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
